.TH "src/asc_pipe_io.cc" 3 "Sat Jan 15 2022" "Version 0.1" "ArduinoSerialControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/asc_pipe_io.cc \- Reading from named pipe and sending commands to arduino through \fBAscSerialIO\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'asc_pipe_io\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <cstring>\fP
.br

.SH "Detailed Description"
.PP 
Reading from named pipe and sending commands to arduino through \fBAscSerialIO\fP\&. 


.PP
\fBAuthor\fP
.RS 4
Alperen BAYRAMOĞLU 
.RE
.PP
\fBDate\fP
.RS 4
2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ArduinoSerialControl from the source code\&.
