.TH "src/asc_serial_io.hpp" 3 "Sat Jan 15 2022" "Version 0.1" "ArduinoSerialControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/asc_serial_io.hpp \- Initializing and communication with arduino on serial port\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <termios\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAscSerialIO\fP"
.br
.RI "ArduinoSerialControl Serial Input/Output\&. "
.in -1c
.SH "Detailed Description"
.PP 
Initializing and communication with arduino on serial port\&. 


.PP
\fBAuthor\fP
.RS 4
Alperen BAYRAMOĞLU 
.RE
.PP
\fBDate\fP
.RS 4
2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ArduinoSerialControl from the source code\&.
